language: node_js
node_js:
  - "14"

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - sakmanal@gmail.com
    on_success: always  # default: change (when the build status changes)
    on_failure: always

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

install:
  - npm install

build_and_test:
  - npm run build -- --prod
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessCI

deploy:
  - npm install -g firebase-tools
  - firebase deploy --only hosting --token $FIREBASE_TOKEN


